### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by WednesdayAd** [karthikkbala/MISP-QRadar-Integration#2]
Hello.
I've try to integration MISP 2.4.103 with Qradar. After

> python3 integration.py >> /var/log/misp-integration.log &

I have some error with JSONDecodeError

Job "socket_check_qradar (trigger: interval[1:00:00], next run at: 2019-03-13 10:04:36 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "integration.py", line 105, in socket_check_qradar
    socket_check_misp()
  File "integration.py", line 115, in socket_check_misp
    validate_refSet()
  File "integration.py", line 48, in validate_refSet
    get_misp_data(refSet_etype)
  File "integration.py", line 58, in get_misp_data
    json_data = misp_response.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Please tell me what i'm doing wrong.

**Comment by ameerprakash** [comment]
Hi,

I am also getting the similar error, how did you resolve this issue?

**Comment by ashmaind** [comment]
I am also getting same error. Can anyone help.
